group = "example"
project = "test"

[resources.basic_info]
name_info = {default_name = "hello"}
type_info = {}
ext = {}
fields = [
    {name_info = {default_name = "id", camel_name="id"},  type_info= {java="Long"}},
]


